---
title: "Golde Age vs Neo Liberalism Period"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

```{r, data, echo = FALSE}
library(knitr)
Fifth <- factor(1:5, labels = rev(c("Bottom Fifth", "Second Fifth", "Third Fifth", "Fourth Fifth", "Top Fifth")))
Golden.Age <- rev(c(122, 101, 113, 115, 99))
Neo.Liberal <- rev(c(-4, 7, 15, 25, 55))
Income.Gains.df <- data.frame(Fifth, Golden.Age, Neo.Liberal)
str(Income.Gains.df)
kable(Income.Gains.df)
```

## Bar Plots

```{r, barplots, echo = FALSE, fig.width = 12, fig.height = 6}
# png(file = "../pics/OECD_Top_Income_Shares_72dpi.png", width = 864, height = 504)
# png(file = "../pics/OECD_Top_Income_Shares_300dpi.png", width = 1280, height = 747)
# par(mfrow = c(1, 2))
par(mfrow = c(1, 2), mai = c(1.0, 1.8, 0.8, 0.4) + 0.2)
x1 <- barplot(Golden.Age, horiz = TRUE, col = "darkorange", axes = FALSE, names.arg = "", xlim = c(0, 130), space = 0.5, las = 1, axisnames = TRUE)
# x1 <- barplot(Top_1_shares[o.top_1], col = "cyan", axes = TRUE, names.arg = Country[o.top_1], xlim = c(0, 25), space = 0.5, las = 1)
# x1 <- barplot(Top_1_shares, horiz = TRUE, col = "cyan", axes = FALSE, names.arg = Country, xlim = c(0, 25), space = 0.5, las = 1)
title.1 <- "1947 ~ 1979"
title(main = title.1, cex.main = 2.0)
abline(v = 0, lwd = 5)
# title(main = "상위 1% 소득점유율(%)")
# text(Top_1_shares[o.top_1], x1, labels = Top_1_shares[o.top_1], cex = 1)
text(20, x1, labels = Fifth, cex = 1)
text(Golden.Age - 10, x1, labels = paste(Golden.Age, "%", sep =""), cex = 1)
# text(Top_1_shares + 2.0, x1, labels = Top_1_shares, cex = 1)
x2 <- barplot(Neo.Liberal, horiz = TRUE, col = "green", axes = FALSE, names.arg = Fifth, xlim = c(0, 80), space = 0.5, las = 1, axisnames = TRUE)
title.2 <- "1980 ~ 2009"
title(main = title.2, cex.main = 2.0)
abline(v = 0, lwd = 5)
# title(main = "상위 10% 소득점유율(%)")
text(Neo.Liberal + c(rep(5, 4), 10), x2, labels = paste(Neo.Liberal, "%", sep = ""), cex = 1)
# text(Top_10_shares + 6.0, x10, labels = Top_10_shares, cex = 1)
# dev.copy(png, file = "../pics/OECD_Top_Income_Shares_2012.png", width = 960, height = 560)
# dev.off()
```

