---
title: "공공부문 부채 추이_자료"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r, data preparation, message = FALSE, echo = FALSE, results = 'markup'}
options(digits = 4)
library(xlsx)
library(knitr)
D1.df <- read.xlsx("../data/D1.xlsx", sheetIndex = 1, header = TRUE, colClasses = rep("numeric", 11))
D2_D3.df <- read.xlsx("../data/D2_D3.xlsx", sheetIndex = 1, header = TRUE, colClasses = rep("numeric", 8))
kable(D1.df)
kable(D2_D3.df)
names(D1.df) <- c("year", "D1", "p1.gdp", "central.g.l", "n.debt", "n.bond", "h.bond", "f.bond", "loan", "action", "local.g.l")
names(D2_D3.df) <- c("year", "D2", "p2.gdp", "D3", "p3.gdp", "n.f.p.c.l", "p4.gdp", "internal.ex")
D1.df <- D1.df[nrow(D1.df):1, ]
D2_D3.df <- D2_D3.df[nrow(D2_D3.df):1, ]
# str(D1.df)
# str(D2_D3.df)
kable(D1.df)
kable(D2_D3.df)
```

```{r, public debt, eval = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_Top_Income_Share_vs_MTR_72dpi_kr.png", width = 864, height = 486)
# png(file = "../pics/US_Top_Income_Share_vs_MTR_300dpi_kr.png", width = 1280, height = 720)
par(mar = c(5, 6, 4, 6) + 0.1)
par(family = "HCR Dotum LVT")
plot(year, D1, type = "b", axes = FALSE, ann = FALSE, ylim = c(200, 1000))
points(year[3:6], D2, type = "b", pch = 2, col = "blue")
points(year[3:6], D3, type = "b", pch = 0, col = "red")
box()
axis(side = 1, at = 2009:2015, labels = 2009:2015)
axis(side = 2, at = seq(200, 1000, by = 200), labels = seq(200, 1000, by = 200), las = 1, ylab = "규모(조원)")
mtext("공공부문 부채", side = 2, line = 3)
par(new = TRUE)
plot(year, p1.gdp, type ="b", lty = 3, axes = FALSE, ann = FALSE, ylim = c(25, 70))
points(year[3:6], p2.gdp, type = "b", pch = 2, col = "blue", lty = 3)
points(year[3:6], p3.gdp, type = "b", pch = 0, col = "red", lty = 3)
axis(side = 4, at = seq(25, 70, by = 5), labels = seq(25, 70, by = 5), las = 1)
mtext("GDP 대비(%)", side = 4, line = 3)
title(main = "공공부문 부채 추이", xlab = "연도", cex.main = 2)
text(x = 2012.5, y = c(41.7, 46.5, 66), labels = c("국가 채무", "일반정부 부채", "공공부문 부채"), cex = 1.2)
text(x = 2014, y = c(34, 40, 46, 51, 63, 69), labels = c("35.9%", "41.8%", "533.2조", "620.6조", "64.5%", "957.3조"))
text(x = 2009, y = c(29, 36), labels = c("31.2%", "359.6조"))
text(x = 2015, y = c(36, 49), labels = c("37.9%", "590.5조"))
text(x = c(2010.75, 2011), y = c(34.5, 42), labels = c("34.5%", "459.2조"))
text(x = 2011, y = c(54, 58.5), labels = c("753.3조", "56.5%"))
text(x = 2009.7, y = 65, labels = "실선은 부채 규모(조원)\n점선은 GDP대비(%)", cex =  1.5)
dev.copy(png, file ="../pics/Kor_Public_Debt.png", width = 960, height = 540)
dev.off()
``` 

```{r, save, echo = FALSE}
save.image("./Kor_N_Debt.rda")
```
