#### 1. Data for US Top Income Shares

다음 물음에 답하시오.


##### 1.1

다음 문서에서 'E. Saez 교수의 홈페이지'는 URL이다. 적절한 코드를 고르시오.

가. `(E. Saez 교수의 홈페이지)(http://elsa.berkeley.edu/~saez/)`

나. `(E. Saez 교수의 홈페이지)[http://elsa.berkeley.edu/~saez/]`

다. `[E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)`

라. `[E. Saez 교수의 홈페이지][http://elsa.berkeley.edu/~saez/]`

> 준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 
> [`TabFig2015prel.xls`](http://eml.berkeley.edu//~saez/TabFig2015prel.xls)` 를 손봐서 불러들인 것이다.


```{r, data preparation, message = FALSE, echo = TRUE, results = 'hide'}
options(digits = 3)
library(xlsx)
US.top.income.shares.15 <- read.xlsx("../data/TabFig2015prel.xlsx", sheetIndex = 9, sheetName = "Table A3", startRow = 6, endRow = 108, colIndex = c(1:7, 9:13), colClasses = c("integer", rep("numeric", 12)), header = FALSE)
v.names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
names(US.top.income.shares.15) <- v.names
str(US.top.income.shares.15)
ls()
save.image(file = "US_top_income_shares_2015.RData")
```

##### 1.2 

위의 코드 묶음에서 `library(xlsx)`가 작동하기 위해서는 다음 중 어떤 코드가 먼저 수행되었어야 하는가?

가. `install.packages("xlsx")`

나. `installed.packages("xlsx")`

다. `update.packages("xlsx")`

라. `download.packages("xlsx")`

##### 1.3

위의 코드로부터 읽어들이고자 하는 엑셀 자료는 몇 줄짜리인가?

가. 101줄

나. 102줄

다. 103줄

라. 104줄

##### 1.4

다음 중 반드시 필요한 설정은 무엇인가?

가. `sheetIndex = 9`

나. `endRow = 108`

다. `colIndex = c(1:7, 9:13)`

라. `header = FALSE`

##### 1.5

`names(US.top.income.shares.15) <- v.names`를 주석처리하면, 각 변수들의 이름은 어떻게 될 것인가?

가. `X1, X2, ..., X13`

나. `V1, V2, ..., V13`

다. `A1, A2, ..., A13`

라. `A, B, ..., M`

##### 1.6

`ls()`의 결과로 옳게 나온 것은?

가. `## [1] "US.top.income.shares.15"`

나. `## [1] "v.names"`

다. `## [1] "US.top.income.shares.15", "v.names"`

라. `## [1] "v.names", "US.top.income.shares.15"`

##### 1.7

`save.image(file = "US_top_income_shares_2015.RData")`의 결과물을 읽어들이려면 필요한 코드는?

가. `getwd("US_top_income_shares_2015.RData")`

나. `read.table("US_top_income_shares_2015.RData")`

다. `load("US_top_income_shares_2015.RData")`

라. `attach("US_top_income_shares_2015.RData")`

<P style = "page-break-before:always">
