---
title: "US Top Income Share 2014"
author: "coop711"
date: "2015년 5월 3일"
output: html_document
---

Data Preparation
----------------

준비한 자료는  E. Saez 교수의 홈페이지에 있는 TabFig2014prel.xls 인데 이를 약간의 작업을 거쳐 R에서 불러들이기 편하게 고쳐놓았다. 

```{r}
options(digits=2)
library(xlsx)
load("US_top_income_share_2014.rda")
#US.top.income.shares.14 <- read.xlsx("./data/TabFig2014prel.xlsx", sheetIndex = 9, sheetName = "Table A3", startRow = 6, endRow = 107, colIndex = c(1:7, 9:13), header = FALSE)
# v.names <- read.xlsx("./data/TabFig2014prel.xlsx", sheetName = "Table A3", startRow = 4, endRow = 4, colIndex = c(2:7, 9:14), colClasses = character, header = FALSE)
#str(US.top.income.shares.14)
v.names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
names(US.top.income.shares.14) <- v.names
#str(US.top.income.shares.14)
ls()
```

작업을 마친 자료파일은 `US.top.income.shares.14`이며, 이 자료의 구조와 앞의 몇 열의 값은 다음과 같다.

```{r}
str(US.top.income.shares.14)
US.top.income.shares.14[, 1:8]
```

이 중에서 소득 상위 10%(`P90_100`)를 상위 1%(`P99_100`), 차상위 4%(`P95_99`), 차차상위 5%(`P90_95`)로 나누어 그 몫의 변화를 살펴보자. 우선 밋밋하게 상위 1%의 소득 점유율 변화만 그려보면,

```{r fig.width=12, fig.height=8}
plot(P99_100~Year, data=US.top.income.shares.14)
```

최소한의 정보를 주기 위하여 각 자료의 최대값, 최소값을 고려하여 y-축의 범위를 `ylim=c(5,25)`로 설정하고, x-축의 눈금은 비워둔다. 점들을 선으로 이어주고, 점은 다시 삼각형 모양으로 바꾼다.

```{r fig.width=12, fig.height=8}
plot(P99_100~Year,data=US.top.income.shares.14, xlab="연도", ylab="소득점유(%)", ylim=c(5,25), xaxt="n", type="b",pch=17)
```

이제 x-축에는 연도를 10년 단위로 표시하고, `lines()`를 이용하여 차상위4%와 차차상위5%의 소득 점유율 변화를 함께 그린다.

```{r fig.width=12, fig.height=8}
plot(P99_100~Year,data=US.top.income.shares.14, xlab="연도", ylab="소득점유(%)", ylim=c(5,25), xaxt="n", type="b",pch=17)
axis(side=1, at=seq(1910, 2010, by=10), labels=seq(1910, 2010, by=10))
lines(P95_99~Year,data=US.top.income.shares.14,type="b", pch=17, col="red")
lines(P90_95~Year,data=US.top.income.shares.14,type="b", pch=17, col="blue")
```

도표의 가독성을 높이기 위하여 x-축과 y-축을 가로지르는 격자를 설치한다.


```{r fig.width=12, fig.height=8}
plot(P99_100~Year,data=US.top.income.shares.14, xlab="연도", ylab="소득점유(%)", ylim=c(5,25), xaxt="n", type="b",pch=17)
axis(side=1, at=seq(1910, 2010, by=10), labels=seq(1910, 2010, by=10))
lines(P95_99~Year,data=US.top.income.shares.14,type="b", pch=17, col="red")
lines(P90_95~Year,data=US.top.income.shares.14,type="b", pch=17, col="blue")
abline(h=seq(5,25, by=5), lty=2)
abline(v=seq(1910, 2010, by=10), lty=2)
```

TabFig2014prel.xls의 Table 0 시트에 나와 있는 정보를 활용하여 범례를 만든다.

```{r fig.width=12, fig.height=8}
plot(P99_100~Year,data=US.top.income.shares.14, xlab="연도", ylab="소득점유(%)", ylim=c(5,25), xaxt="n", type="b",pch=17)
axis(side=1, at=seq(1910, 2010, by=10), labels=seq(1910, 2010, by=10))
lines(P95_99~Year,data=US.top.income.shares.14,type="b", pch=17, col="red")
lines(P90_95~Year,data=US.top.income.shares.14,type="b", pch=17, col="blue")
abline(h=seq(5,25, by=5), lty=2)
abline(v=seq(1910, 2010, by=10), lty=2)
legend(x=1945, y=25, legend=c("99-100%:$423,090 이상(2014년 기준)","95-99%:$174,240-$423,090","90-95%:$121,360-$174,240"), pch=17, col=c("black", "red", "blue"))
```

메인 타이틀을 입력하고, 상위1%의 소득점유율이 최고에 달했던 연도를 표시한다.

```{r fig.width=12, fig.height=8}
plot(P99_100~Year,data=US.top.income.shares.14, xlab="연도", ylab="소득점유(%)", ylim=c(5,25), xaxt="n", type="b",pch=17)
axis(side=1, at=seq(1910, 2010, by=10), labels=seq(1910, 2010, by=10))
lines(P95_99~Year,data=US.top.income.shares.14,type="b", pch=17, col="red")
lines(P90_95~Year,data=US.top.income.shares.14,type="b", pch=17, col="blue")
abline(h=seq(5,25, by=5), lty=2)
abline(v=seq(1910, 2010, by=10), lty=2)
legend(x=1945, y=25, legend=c("99-100%:$423,090 이상(2014년 기준)","95-99%:$174,240-$423,090","90-95%:$121,360-$174,240"), pch=17, col=c("black", "red", "blue"))
title(main="미국 소득 상위 10%의 점유율 분할")
text(x=c(1928, 2007), y=c(24, 23.5), labels=c("1928", "2007"), pos=3)
```

역사적으로 각 시기를 어떻게 부르고 있는지 텍스트를 추가한다.

```{r fig.width=12, fig.height=8}
plot(P99_100~Year,data=US.top.income.shares.14, xlab="연도", ylab="소득점유(%)", ylim=c(5,25), xaxt="n", type="b",pch=17)
axis(side=1, at=seq(1910, 2010, by=10), labels=seq(1910, 2010, by=10))
lines(P95_99~Year,data=US.top.income.shares.14,type="b", pch=17, col="red")
lines(P90_95~Year,data=US.top.income.shares.14,type="b", pch=17, col="blue")
abline(h=seq(5,25, by=5), lty=2)
abline(v=seq(1910, 2010, by=10), lty=2)
legend(x=1945, y=25, legend=c("99-100%:$423,090 이상(2014년 기준)","95-99%:$174,240-$423,090","90-95%:$121,360-$174,240"), pch=17, col=c("black", "red", "blue"))
title(main="미국 소득 상위 10%의 점유율 분할")
text(x=c(1928, 2007), y=c(24, 23.5), labels=c("1928", "2007"), pos=3)
text(x=1935, y=22, label="(가)", cex=2.0, col="red")
text(x=1960, y=8, label="(나)", cex=2.0, col="red")
text(x=2012, y=17.5, label="(다)", cex=2.0, col="red")
```

뒷 정리
-------


