---
title: "US Top Income Share 1913 ~ 2014"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r, setup , include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Data Preparation

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 [`TabFig2014prel.xls`](http://eml.berkeley.edu//~saez/TabFig2014prel.xls) 를 손봐서 불러들인 것이다. 

```{r, data preparation, echo = FALSE, message = FALSE, results = 'hide'}
options(digits = 2)
library(xlsx)
load("US_top_income_shares_2014_add.rda")
# US.top.income.shares.14 <- read.xlsx("../data/TabFig2014prel.xlsx", sheetIndex = 9, sheetName = "Table A3", startRow = 6, endRow = 107, colIndex = c(1:7, 9:13), header = FALSE)
# v.names <- read.xlsx("./data/TabFig2014prel.xlsx", sheetName = "Table A3", startRow = 4, endRow = 4, colIndex = c(2:7, 9:14), colClasses = character, header = FALSE)
#str(US.top.income.shares.14)
v.names <- c("Year", "P90_100", "P95_100", "P99_100", "P99.5_100", "P99.9_100", "P99.99_100", "P90_95", "P95_99", "P99_99.5", "P99.5_99.9", "P99.9_99.99")
names(US.top.income.shares.14) <- v.names
ls()
```

<!--작업을 마친 자료파일은 `US.top.income.shares.14`이며, 이 자료의 구조와 앞의 몇 열의 값은 다음과 같다.-->

```{r, data structure, echo = FALSE, results = 'hide'}
library(knitr)
str(US.top.income.shares.14)
```

```{r, data for Table 3, echo = FALSE}
kable(US.top.income.shares.14[c(11:20, 41:51, 91:102),])
```


### Top 10%

소득 상위 10%(`P90_100`)를 상위 1%(`P99_100`), 차상위 4%(`P95_99`), 차차상위 5%(`P90_95`)로 분할

```{r, partition top 10, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_1-4-5_2014_72dpi.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_1-4-5_2014_300dpi.png", width = 1280, height = 720)
x.lab <- "Year"
y.lab <- "Income Shares (%)"
plot(P99_100 ~ Year, data = US.top.income.shares.14, xlab = x.lab, ylab = y.lab, ylim = c(5, 25), xaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2010, by = 10), labels = seq(1910, 2010, by = 10))
lines(P95_99 ~ Year, data = US.top.income.shares.14, type = "b", pch = 17, col = "red")
lines(P90_95 ~ Year, data = US.top.income.shares.14, type = "b", pch = 17, col = "blue")
abline(h = seq(5, 25, by = 5), lty = 3)
abline(v = seq(1910, 2010, by = 10), lty = 3)
legend.text.1 <- c("Top 1% (incomes above $423,090 in 2014)", "Top 5-1% (incomes between $174,240 and $423,090)", "Top 10-5% (incomes between $121,360 and $174,240)")
legend(x = 1945, y = 25, legend = legend.text.1, pch = 17, col = c("black", "red", "blue"))
main.title.1 <- "Decomposing the Top 10% US Income Share (1913 ~ 2014)"
title(main = main.title.1)
text(x = c(1928, 2007), y = c(24, 23.5), labels = c("1928", "2007"), pos = 3)
times.label <- c("The Great\nDepression", "The Great\nProsperity", "The Great\nRecession")
text(x = c(1935, 1960, 2013.5), y = c(22, 8, 18), label = times.label, cex = 1.0, col = "red")
# dev.copy(png, file = "../pics/US_top_income_share_1-4-5_2014.png", width = 960, height = 600)
# dev.off()
```

----

----

----

### Top 1% 

소득 상위 1%(`P99_100`)를 상위 0.1%(`P99.9_100`), 차상위 0.4%(`P99.5_99.9`), 차차상위 0.5%(`P99_99.5`)로 분할

```{r, partiotion top 1, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_0.1-0.4-0.5_2014_72dpi.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_0.1-0.4-0.5_2014_300dpi.png", width = 1280, height = 720)
plot(P99.9_100 ~ Year, data = US.top.income.shares.14, xlab = x.lab, ylab = y.lab, ylim = c(0, 15), xaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2010, by = 10), labels = seq(1910, 2010, by = 10))
lines(P99.5_99.9 ~ Year, data = US.top.income.shares.14, type = "b", pch = 17, col = "red")
lines(P99_99.5 ~ Year, data = US.top.income.shares.14, type = "b", pch = 17, col = "blue")
abline(h = seq(0, 15, by = 5), lty = 3)
abline(v = seq(1910, 2010, by = 10), lty = 3)
legend.text.2 <- c("Top 0.1% (incomes above $1,894,100 in 2014)", "Top 0.5-0.1% (incomes between $646,550 and $1,894,100)", "Top 1-0.5% (incomes between $423,090 and $646,550)")
legend(x = 1945, y = 15, legend = legend.text.2, pch = 17, col = c("black", "red", "blue"))
main.title.2 <- "Decomposing the Top 1% US Income Share (1913 ~ 2014)"
title(main = main.title.2)
text(x = c(1928, 2007), y = c(12, 12.5), labels = c("1928", "2007"), pos = 3)
text(x = c(1935, 1960, 2013.5), y = c(9, 2, 8), label = times.label, cex = 1.0, col = "red")
# dev.copy(png, file = "../pics/US_top_income_share_0.1-0.4-0.5_2014.png", width = 960, height = 600)
# dev.off()
```

----

----

----

---

### Top 0.1% 

소득 상위 0.1%(`P99_100`)를 상위 0.01%(`P99.99_100`)와 다음 0.09%(`P99_9.99.99`)로 분할

```{r, partiotion top 1 0.01 vs 0.99, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_top_income_share_0.01-0.09_2014_72dpi.png", width = 864, height = 486)
# png(file = "../pics/US_top_income_share_0.01-0.09_2014_300dpi.png", width = 1280, height = 720)
plot(P99.99_100 ~ Year, data = US.top.income.shares.14, xlab = x.lab, ylab = y.lab, ylim = c(0, 8), xaxt = "n", type = "b", pch = 17)
axis(side = 1, at = seq(1910, 2010, by = 10), labels = seq(1910, 2010, by = 10))
lines(P99.9_99.99 ~ Year, data = US.top.income.shares.14, type = "b", pch = 17, col = "blue")
abline(h = seq(0, 8, by = 2), lty = 3)
abline(v = seq(1910, 2010, by = 10), lty = 3)
legend.text.3 <- c("Top 0.01% (incomes above $9,497,900 in 2014)", "Top 0.1-0.01% (incomes between $1,894,100 and $9,497,900)")
legend(x = 1945, y = 8, legend = legend.text.3, pch = 17, col = c("black", "blue"))
main.title.3 <- "Decomposing the Top 0.1% US Income Share (1913 ~ 2014)"
title(main = main.title.3)
text(x = c(1928, 2007), y = c(6.5, 6.3), labels = c("1928", "2007"), pos = 3)
text(x = c(1935, 1960, 2013.5), y = c(5.6, 2.8, 3.4), label = times.label, cex = 1.0, col = "red")
# dev.print(png, file = "../pics/US_top_income_share_0.01-0.09_2014.png", width = 960, height = 600)
# dev.off()
```

----

----

----

## ggplot

### Data Reshaping

`reshape2` 패키지를 이용하여 wide format 을 long format 으로 변환하고 작업

```{r, reshape, echo = FALSE}
library(reshape2)
data.10 <- US.top.income.shares.14[c("Year", "P99_100", "P95_99", "P90_95")]
data.10.melt <- melt(data.10, id.vars = "Year", measure.vars = c("P99_100", "P95_99", "P90_95"), variable.name = "Percentiles", value.name = "Share")
# str(data.10.melt)
data.1 <- US.top.income.shares.14[c("Year", "P99.9_100", "P99.5_99.9", "P99_99.5")]
data.1.melt <- melt(data.1, id.vars = "Year", measure.vars = c("P99.9_100", "P99.5_99.9", "P99_99.5"), variable.name = "Percentiles", value.name = "Share")
# str(data.1.melt)
data.01 <- US.top.income.shares.14[c("Year", "P99.99_100", "P99.9_99.99")]
data.01.melt <- melt(data.01, id.vars = "Year", measure.vars = c("P99.99_100", "P99.9_99.99"), variable.name = "Percentiles", value.name = "Share")
# str(data.01.melt)
```

### Top 10% 

```{r, Top 10 percent, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
# source("./theme_kr.R")
library(ggplot2)
g0 <- ggplot(data.10.melt, aes(x = Year, y = Share, colour = Percentiles)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, aes(fill = Percentiles), size = 2, na.rm = TRUE) + 
  ylim(5, 25)
# g0
g1 <- g0 + 
  theme_bw()
# g1
g2 <- g1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# g2
g3 <- g2 + 
  scale_x_continuous(breaks = seq(1910, 2010, by = 10))
# g3
g4 <- g3 + 
#   theme.kr + 
   xlab(x.lab) + 
   ylab(y.lab)
# g4
g5 <- g4 + 
   ggtitle(main.title.1) + 
   theme(plot.title = element_text(size = 20))
# g5
g6 <- g5 + 
   labs(colour = "Income Fractile", fill = "Income Fractile")
# g6
g7 <- g6 + 
   scale_colour_manual(name = "", values = c("black", "red", "blue"), labels = legend.text.1) +
   scale_fill_manual(name = "", values = c("black", "red", "blue"), labels = legend.text.1)
# g7
g8 <- g7 + 
   theme(legend.position =  c(0.5, 0.85))
# g8
g9 <- g8 + 
   guides(colour ="none")
# g9
g10 <- g9 + 
   theme(legend.title = element_blank(), legend.background = element_rect(fill = "white", colour = "black"))
# g10
g11 <- g10 + 
   theme(legend.key = element_blank())
# g11
g12 <- g11 + 
   annotate("text", x = c(1928, 2007), y = c(24.5, 24), label = c(1928, 2007))
# g12
g13 <- g12 + 
#  annotate("text", x = c(1935, 1960, 2014), y = c(22, 8, 18), label = times.label, colour = "red", family = "HCR Dotum LVT", size = 8)
  annotate("text", x = c(1935, 1960, 2014), y = c(22, 8, 18), label = times.label, colour = "red", size = 4)

```

```{r, Top 10 percent ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
g13
# ggsave("../pics/US_top_income_share_1-4-5_2014_ggplot.png", width = 12, height = 6.75)
```

### Top 1% 

```{r, Top 1 percent, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
h0 <- ggplot(data.1.melt, aes(x = Year, y = Share, colour = Percentiles)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, aes(fill = Percentiles), size = 2, na.rm = TRUE) + 
  ylim(0, 15)
# h0
h1 <- h0 + 
  theme_bw()
# h1
h2 <- h1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# h2
h3 <- h2 + 
  scale_x_continuous(breaks = seq(1910, 2010, by = 10))
# h3
h4 <- h3 + 
#   theme.kr + 
   xlab(x.lab) + 
   ylab(y.lab)
# h4
h5 <- h4 + 
   ggtitle(main.title.2) + 
   theme(plot.title = element_text(size = 20))
# h5
h6 <- h5 + 
   labs(colour = "Income Fractile", fill = "Income Fractile")
# h6
h7 <- h6 + 
   scale_colour_manual(name = "", values = c("black", "red", "blue"), labels = legend.text.2) +
   scale_fill_manual(name = "", values = c("black", "red", "blue"), labels = legend.text.2)
# h7
h8 <- h7 + 
   theme(legend.position =  c(0.5, 0.85))
# h8
h9 <- h8 + 
   guides(colour ="none")
# h9
h10 <- h9 + 
   theme(legend.title = element_blank(), legend.background = element_rect(fill = "white", colour = "black"))
# h10
h11 <- h10 + 
   theme(legend.key = element_blank())
# h11
h12 <- h11 + 
   annotate("text", x = c(1928, 2007), y = c(12, 12.8), label = c(1928, 2007))
# h12
h13 <- h12 + 
#  annotate("text", x = c(1935, 1960, 2014), y = c(9, 2, 8), label = times.label, colour = "red", family = "HCR Dotum LVT", size = 8)
  annotate("text", x = c(1935, 1960, 2014), y = c(9, 2, 8), label = times.label, colour = "red", size = 4)
```

```{r, Top 1 percent ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
h13
# ggsave("../pics/US_top_income_share_0.1-0.4-0.5_2014_ggplot.png", width = 12, height = 6.75)
```

### Top 0.1% 

```{r, Top 0.1 percent, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
j0 <- ggplot(data.01.melt, aes(x = Year, y = Share, colour = Percentiles)) + 
  geom_line(na.rm = TRUE) + 
  geom_point(shape = 24, aes(fill = Percentiles), size = 2, na.rm = TRUE) + 
  ylim(0, 8)
# j0
j1 <- j0 + 
  theme_bw()
# j1
j2 <- j1 + 
   theme(panel.grid.major = element_line(linetype = "dotted", colour = "black"))
# j2
j3 <- j2 + 
  scale_x_continuous(breaks = seq(1910, 2010, by = 10))
# j3
j4 <- j3 + 
#   theme.kr + 
   xlab(x.lab) + 
   ylab(y.lab)
# j4
j5 <- j4 + 
   ggtitle(main.title.3) + 
   theme(plot.title = element_text(size = 20))
# j5
j6 <- j5 + 
   labs(colour = "Income Fractile", fill = "Income Fractile") 
# j6
j7 <- j6 + 
   scale_colour_manual(name = "", values = c("black", "blue"), labels = legend.text.3) +
   scale_fill_manual(name = "", values = c("black", "blue"), labels = legend.text.3)
# j7
j8 <- j7 + 
   theme(legend.position =  c(0.5, 0.85))
# j8
j9 <- j8 + 
   guides(colour ="none")
# j9
j10 <- j9 + 
   theme(legend.title = element_blank(), legend.background = element_rect(fill = "white", colour = "black"))
# j10
j11 <- j10 + 
   theme(legend.key = element_blank())
# j11
j12 <- j11 + 
   annotate("text", x = c(1928, 2007), y = c(6.8, 6.5), label = c(1928, 2007))
# j12
j13 <- j12 + 
#  annotate("text", x = c(1935, 1960, 2014), y = c(5.6, 2.8, 3.0), label = times.label, colour = "red", family = "HCR Dotum LVT", size = 8)
  annotate("text", x = c(1935, 1960, 2014), y = c(5.6, 2.8, 3.5), label = times.label, colour = "red", size = 4)
```

```{r, Top 0.1 percent ggsave, warning = FALSE, echo = FALSE, fig.width = 12, fig.height = 6.75}
j13
# ggsave("../pics/US_top_income_share_0.01-0.09_2014_ggplot.png", width = 12, height = 6.75)
```


<!--## 뒷 정리

```{r, save.image}
# save.image(file = "US_top_income_shares_2014_add.rda")
```
-->
